'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EmployeeRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="R_DTOBase", [Namespace]:="http://schemas.datacontract.org/2004/07/R_BackEnd"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EmployeeRef.EmployeeDTO))>  _
    Partial Public Class R_DTOBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmployeeDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmployeeDTO
        Inherits EmployeeRef.R_DTOBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmployeeIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmployeeID() As Integer
            Get
                Return Me.EmployeeIDField
            End Get
            Set
                If (Me.EmployeeIDField.Equals(value) <> true) Then
                    Me.EmployeeIDField = value
                    Me.RaisePropertyChanged("EmployeeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="eCRUDMode", [Namespace]:="http://schemas.datacontract.org/2004/07/R_BackEnd")>  _
    Public Enum eCRUDMode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NormalMode = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AddMode = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EditMode = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DeleteMode = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EmployeeRef.IEmployeeService")>  _
    Public Interface IEmployeeService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_GetRecord", ReplyAction:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_GetRecordResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_GetRecordR_ServiceException"& _ 
            "sFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function Svc_R_GetRecord(ByVal poEntity As EmployeeRef.EmployeeDTO, ByVal poCRUDMode As EmployeeRef.eCRUDMode) As EmployeeRef.EmployeeDTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_Save", ReplyAction:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_SaveResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_SaveR_ServiceExceptionsFaul"& _ 
            "t", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function Svc_R_Save(ByVal poEntity As EmployeeRef.EmployeeDTO, ByVal poCRUDMode As EmployeeRef.eCRUDMode) As EmployeeRef.EmployeeDTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_Delete", ReplyAction:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_DeleteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/R_IServicebaseOf_EmployeeDTO/Svc_R_DeleteR_ServiceExceptionsFa"& _ 
            "ult", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub Svc_R_Delete(ByVal poEntity As EmployeeRef.EmployeeDTO)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IEmployeeServiceChannel
        Inherits EmployeeRef.IEmployeeService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class EmployeeServiceClient
        Inherits System.ServiceModel.ClientBase(Of EmployeeRef.IEmployeeService)
        Implements EmployeeRef.IEmployeeService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Svc_R_GetRecord(ByVal poEntity As EmployeeRef.EmployeeDTO, ByVal poCRUDMode As EmployeeRef.eCRUDMode) As EmployeeRef.EmployeeDTO Implements EmployeeRef.IEmployeeService.Svc_R_GetRecord
            Return MyBase.Channel.Svc_R_GetRecord(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_R_Save(ByVal poEntity As EmployeeRef.EmployeeDTO, ByVal poCRUDMode As EmployeeRef.eCRUDMode) As EmployeeRef.EmployeeDTO Implements EmployeeRef.IEmployeeService.Svc_R_Save
            Return MyBase.Channel.Svc_R_Save(poEntity, poCRUDMode)
        End Function
        
        Public Sub Svc_R_Delete(ByVal poEntity As EmployeeRef.EmployeeDTO) Implements EmployeeRef.IEmployeeService.Svc_R_Delete
            MyBase.Channel.Svc_R_Delete(poEntity)
        End Sub
    End Class
End Namespace
