'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CTM0100SvcRef
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CTM0100SvcRef.ICTM0100Svc")>  _
    Public Interface ICTM0100Svc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICTM0100Svc/GetList", ReplyAction:="http://tempuri.org/ICTM0100Svc/GetListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/ICTM0100Svc/GetListCT_ServiceExceptionsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Function GetList() As System.Collections.Generic.List(Of CTM0100.CTM0100SvcRef.m_karyawan02DTO)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ICTM0100SvcChannel
        Inherits CTM0100SvcRef.ICTM0100Svc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class CTM0100SvcClient
        Inherits System.ServiceModel.ClientBase(Of CTM0100SvcRef.ICTM0100Svc)
        Implements CTM0100SvcRef.ICTM0100Svc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetList() As System.Collections.Generic.List(Of CTM0100.CTM0100SvcRef.m_karyawan02DTO) Implements CTM0100SvcRef.ICTM0100Svc.GetList
            Return MyBase.Channel.GetList
        End Function
    End Class
End Namespace
