'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CTM0100SvcRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CT_DTOBase", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_BackEnd"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(CTM0100SvcRef.m_karyawan01DTO))>  _
    Partial Public Class CT_DTOBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="m_karyawan01DTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class m_karyawan01DTO
        Inherits CTM0100SvcRef.CT_DTOBase
        
        Private CREA_BYField As String
        
        Private CREA_DATEField As Date
        
        Private FOTOField() As Byte
        
        Private GAPOKField As Decimal
        
        Private JABATANField As String
        
        Private JENIS_KELAMINField As String
        
        Private JUM_ANAKField As Integer
        
        Private KODE_PENDIDIKANField As String
        
        Private NAMAField As String
        
        Private NIKField As String
        
        Private TGL_LAHIRField As Date
        
        Private TUN_TRANSPORTField As Decimal
        
        Private UPD_BYField As String
        
        Private UPD_DATEField As Date
        
        Private WARGA_NEGARAField As String
        
        Private WARGA_NEGARA_IDField As String
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property FOTO() As Byte()
            Get
                Return Me.FOTOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FOTOField, value) <> true) Then
                    Me.FOTOField = value
                    Me.RaisePropertyChanged("FOTO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property GAPOK() As Decimal
            Get
                Return Me.GAPOKField
            End Get
            Set
                If (Me.GAPOKField.Equals(value) <> true) Then
                    Me.GAPOKField = value
                    Me.RaisePropertyChanged("GAPOK")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property JABATAN() As String
            Get
                Return Me.JABATANField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JABATANField, value) <> true) Then
                    Me.JABATANField = value
                    Me.RaisePropertyChanged("JABATAN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property JENIS_KELAMIN() As String
            Get
                Return Me.JENIS_KELAMINField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JENIS_KELAMINField, value) <> true) Then
                    Me.JENIS_KELAMINField = value
                    Me.RaisePropertyChanged("JENIS_KELAMIN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property JUM_ANAK() As Integer
            Get
                Return Me.JUM_ANAKField
            End Get
            Set
                If (Me.JUM_ANAKField.Equals(value) <> true) Then
                    Me.JUM_ANAKField = value
                    Me.RaisePropertyChanged("JUM_ANAK")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property KODE_PENDIDIKAN() As String
            Get
                Return Me.KODE_PENDIDIKANField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KODE_PENDIDIKANField, value) <> true) Then
                    Me.KODE_PENDIDIKANField = value
                    Me.RaisePropertyChanged("KODE_PENDIDIKAN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property NAMA() As String
            Get
                Return Me.NAMAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NAMAField, value) <> true) Then
                    Me.NAMAField = value
                    Me.RaisePropertyChanged("NAMA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property NIK() As String
            Get
                Return Me.NIKField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NIKField, value) <> true) Then
                    Me.NIKField = value
                    Me.RaisePropertyChanged("NIK")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property TGL_LAHIR() As Date
            Get
                Return Me.TGL_LAHIRField
            End Get
            Set
                If (Me.TGL_LAHIRField.Equals(value) <> true) Then
                    Me.TGL_LAHIRField = value
                    Me.RaisePropertyChanged("TGL_LAHIR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property TUN_TRANSPORT() As Decimal
            Get
                Return Me.TUN_TRANSPORTField
            End Get
            Set
                If (Me.TUN_TRANSPORTField.Equals(value) <> true) Then
                    Me.TUN_TRANSPORTField = value
                    Me.RaisePropertyChanged("TUN_TRANSPORT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property WARGA_NEGARA() As String
            Get
                Return Me.WARGA_NEGARAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WARGA_NEGARAField, value) <> true) Then
                    Me.WARGA_NEGARAField = value
                    Me.RaisePropertyChanged("WARGA_NEGARA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property WARGA_NEGARA_ID() As String
            Get
                Return Me.WARGA_NEGARA_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WARGA_NEGARA_IDField, value) <> true) Then
                    Me.WARGA_NEGARA_IDField = value
                    Me.RaisePropertyChanged("WARGA_NEGARA_ID")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="eCRUDMode", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_BackEnd")>  _
    Public Enum eCRUDMode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NormalMode = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AddMode = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EditMode = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DeleteMode = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="m_karyawan02DTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class m_karyawan02DTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CREA_BYField As String
        
        Private CREA_DATEField As Date
        
        Private FOTOField() As Byte
        
        Private GAPOKField As Decimal
        
        Private JABATANField As String
        
        Private JENIS_KELAMINField As String
        
        Private JUM_ANAKField As Integer
        
        Private NAMAField As String
        
        Private NIKField As String
        
        Private TGL_LAHIRField As Date
        
        Private TUN_TRANSPORTField As Decimal
        
        Private UPD_BYField As String
        
        Private UPD_DATEField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CREA_BY() As String
            Get
                Return Me.CREA_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREA_BYField, value) <> true) Then
                    Me.CREA_BYField = value
                    Me.RaisePropertyChanged("CREA_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CREA_DATE() As Date
            Get
                Return Me.CREA_DATEField
            End Get
            Set
                If (Me.CREA_DATEField.Equals(value) <> true) Then
                    Me.CREA_DATEField = value
                    Me.RaisePropertyChanged("CREA_DATE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property FOTO() As Byte()
            Get
                Return Me.FOTOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FOTOField, value) <> true) Then
                    Me.FOTOField = value
                    Me.RaisePropertyChanged("FOTO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property GAPOK() As Decimal
            Get
                Return Me.GAPOKField
            End Get
            Set
                If (Me.GAPOKField.Equals(value) <> true) Then
                    Me.GAPOKField = value
                    Me.RaisePropertyChanged("GAPOK")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property JABATAN() As String
            Get
                Return Me.JABATANField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JABATANField, value) <> true) Then
                    Me.JABATANField = value
                    Me.RaisePropertyChanged("JABATAN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property JENIS_KELAMIN() As String
            Get
                Return Me.JENIS_KELAMINField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JENIS_KELAMINField, value) <> true) Then
                    Me.JENIS_KELAMINField = value
                    Me.RaisePropertyChanged("JENIS_KELAMIN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property JUM_ANAK() As Integer
            Get
                Return Me.JUM_ANAKField
            End Get
            Set
                If (Me.JUM_ANAKField.Equals(value) <> true) Then
                    Me.JUM_ANAKField = value
                    Me.RaisePropertyChanged("JUM_ANAK")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property NAMA() As String
            Get
                Return Me.NAMAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NAMAField, value) <> true) Then
                    Me.NAMAField = value
                    Me.RaisePropertyChanged("NAMA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property NIK() As String
            Get
                Return Me.NIKField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NIKField, value) <> true) Then
                    Me.NIKField = value
                    Me.RaisePropertyChanged("NIK")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property TGL_LAHIR() As Date
            Get
                Return Me.TGL_LAHIRField
            End Get
            Set
                If (Me.TGL_LAHIRField.Equals(value) <> true) Then
                    Me.TGL_LAHIRField = value
                    Me.RaisePropertyChanged("TGL_LAHIR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property TUN_TRANSPORT() As Decimal
            Get
                Return Me.TUN_TRANSPORTField
            End Get
            Set
                If (Me.TUN_TRANSPORTField.Equals(value) <> true) Then
                    Me.TUN_TRANSPORTField = value
                    Me.RaisePropertyChanged("TUN_TRANSPORT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property UPD_BY() As String
            Get
                Return Me.UPD_BYField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UPD_BYField, value) <> true) Then
                    Me.UPD_BYField = value
                    Me.RaisePropertyChanged("UPD_BY")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property UPD_DATE() As Date
            Get
                Return Me.UPD_DATEField
            End Get
            Set
                If (Me.UPD_DATEField.Equals(value) <> true) Then
                    Me.UPD_DATEField = value
                    Me.RaisePropertyChanged("UPD_DATE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKm_warga_negaraDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKm_warga_negaraDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WARGA_NEGARAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WARGA_NEGARA_IDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WARGA_NEGARA() As String
            Get
                Return Me.WARGA_NEGARAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WARGA_NEGARAField, value) <> true) Then
                    Me.WARGA_NEGARAField = value
                    Me.RaisePropertyChanged("WARGA_NEGARA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WARGA_NEGARA_ID() As String
            Get
                Return Me.WARGA_NEGARA_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WARGA_NEGARA_IDField, value) <> true) Then
                    Me.WARGA_NEGARA_IDField = value
                    Me.RaisePropertyChanged("WARGA_NEGARA_ID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKm_jabatanDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKm_jabatanDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JABATANField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property JABATAN() As String
            Get
                Return Me.JABATANField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JABATANField, value) <> true) Then
                    Me.JABATANField = value
                    Me.RaisePropertyChanged("JABATAN")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LKm_pendidikanDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LKm_pendidikanDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KODE_PENDIDIKANField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PENDIDIKANField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property KODE_PENDIDIKAN() As String
            Get
                Return Me.KODE_PENDIDIKANField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KODE_PENDIDIKANField, value) <> true) Then
                    Me.KODE_PENDIDIKANField = value
                    Me.RaisePropertyChanged("KODE_PENDIDIKAN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PENDIDIKAN() As String
            Get
                Return Me.PENDIDIKANField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PENDIDIKANField, value) <> true) Then
                    Me.PENDIDIKANField = value
                    Me.RaisePropertyChanged("PENDIDIKAN")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RoleDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RoleDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Add_PermitField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private App_IdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Delete_PermitField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Edit_PermitField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Read_PermitField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Add_Permit() As Boolean
            Get
                Return Me.Add_PermitField
            End Get
            Set
                If (Me.Add_PermitField.Equals(value) <> true) Then
                    Me.Add_PermitField = value
                    Me.RaisePropertyChanged("Add_Permit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property App_Id() As String
            Get
                Return Me.App_IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.App_IdField, value) <> true) Then
                    Me.App_IdField = value
                    Me.RaisePropertyChanged("App_Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Delete_Permit() As Boolean
            Get
                Return Me.Delete_PermitField
            End Get
            Set
                If (Me.Delete_PermitField.Equals(value) <> true) Then
                    Me.Delete_PermitField = value
                    Me.RaisePropertyChanged("Delete_Permit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Edit_Permit() As Boolean
            Get
                Return Me.Edit_PermitField
            End Get
            Set
                If (Me.Edit_PermitField.Equals(value) <> true) Then
                    Me.Edit_PermitField = value
                    Me.RaisePropertyChanged("Edit_Permit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Read_Permit() As Boolean
            Get
                Return Me.Read_PermitField
            End Get
            Set
                If (Me.Read_PermitField.Equals(value) <> true) Then
                    Me.Read_PermitField = value
                    Me.RaisePropertyChanged("Read_Permit")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CTM0100SvcRef.ICTM0100Svc")>  _
    Public Interface ICTM0100Svc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_GetRecord", ReplyAction:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_GetRecordResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_GetRecordCT_ServiceEx"& _ 
            "ceptionsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Function Svc_CT_GetRecord(ByVal poEntity As CTM0100SvcRef.m_karyawan01DTO, ByVal poCRUDMode As CTM0100SvcRef.eCRUDMode) As CTM0100SvcRef.m_karyawan01DTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_Save", ReplyAction:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_SaveResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_SaveCT_ServiceExcepti"& _ 
            "onsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Function Svc_CT_Save(ByVal poEntity As CTM0100SvcRef.m_karyawan01DTO, ByVal poCRUDMode As CTM0100SvcRef.eCRUDMode) As CTM0100SvcRef.m_karyawan01DTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_Delete", ReplyAction:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_DeleteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/CT_IServicebaseOf_m_karyawan01DTO/Svc_CT_DeleteCT_ServiceExcep"& _ 
            "tionsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Sub Svc_CT_Delete(ByVal poEntity As CTM0100SvcRef.m_karyawan01DTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICTM0100Svc/GetList", ReplyAction:="http://tempuri.org/ICTM0100Svc/GetListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/ICTM0100Svc/GetListCT_ServiceExceptionsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Function GetList() As System.Collections.Generic.List(Of CTM0100SvcRef.m_karyawan02DTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICTM0100Svc/GetLKm_warga_negara", ReplyAction:="http://tempuri.org/ICTM0100Svc/GetLKm_warga_negaraResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/ICTM0100Svc/GetLKm_warga_negaraCT_ServiceExceptionsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Function GetLKm_warga_negara(ByVal poEntity As CTM0100SvcRef.LKm_warga_negaraDTO) As System.Collections.Generic.List(Of CTM0100SvcRef.LKm_warga_negaraDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICTM0100Svc/GetLKm_jabatan", ReplyAction:="http://tempuri.org/ICTM0100Svc/GetLKm_jabatanResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/ICTM0100Svc/GetLKm_jabatanCT_ServiceExceptionsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Function GetLKm_jabatan() As System.Collections.Generic.List(Of CTM0100SvcRef.LKm_jabatanDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICTM0100Svc/GetLKm_pendidikan", ReplyAction:="http://tempuri.org/ICTM0100Svc/GetLKm_pendidikanResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/ICTM0100Svc/GetLKm_pendidikanCT_ServiceExceptionsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Function GetLKm_pendidikan() As System.Collections.Generic.List(Of CTM0100SvcRef.LKm_pendidikanDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICTM0100Svc/GetRole", ReplyAction:="http://tempuri.org/ICTM0100Svc/GetRoleResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CT_Common.CT_ServiceExceptions), Action:="http://tempuri.org/ICTM0100Svc/GetRoleCT_ServiceExceptionsFault", Name:="CT_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/CT_Common")>  _
        Function GetRole() As System.Collections.Generic.List(Of CTM0100SvcRef.RoleDTO)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICTM0100SvcChannel
        Inherits CTM0100SvcRef.ICTM0100Svc, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CTM0100SvcClient
        Inherits System.ServiceModel.ClientBase(Of CTM0100SvcRef.ICTM0100Svc)
        Implements CTM0100SvcRef.ICTM0100Svc
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Svc_CT_GetRecord(ByVal poEntity As CTM0100SvcRef.m_karyawan01DTO, ByVal poCRUDMode As CTM0100SvcRef.eCRUDMode) As CTM0100SvcRef.m_karyawan01DTO Implements CTM0100SvcRef.ICTM0100Svc.Svc_CT_GetRecord
            Return MyBase.Channel.Svc_CT_GetRecord(poEntity, poCRUDMode)
        End Function
        
        Public Function Svc_CT_Save(ByVal poEntity As CTM0100SvcRef.m_karyawan01DTO, ByVal poCRUDMode As CTM0100SvcRef.eCRUDMode) As CTM0100SvcRef.m_karyawan01DTO Implements CTM0100SvcRef.ICTM0100Svc.Svc_CT_Save
            Return MyBase.Channel.Svc_CT_Save(poEntity, poCRUDMode)
        End Function
        
        Public Sub Svc_CT_Delete(ByVal poEntity As CTM0100SvcRef.m_karyawan01DTO) Implements CTM0100SvcRef.ICTM0100Svc.Svc_CT_Delete
            MyBase.Channel.Svc_CT_Delete(poEntity)
        End Sub
        
        Public Function GetList() As System.Collections.Generic.List(Of CTM0100SvcRef.m_karyawan02DTO) Implements CTM0100SvcRef.ICTM0100Svc.GetList
            Return MyBase.Channel.GetList
        End Function
        
        Public Function GetLKm_warga_negara(ByVal poEntity As CTM0100SvcRef.LKm_warga_negaraDTO) As System.Collections.Generic.List(Of CTM0100SvcRef.LKm_warga_negaraDTO) Implements CTM0100SvcRef.ICTM0100Svc.GetLKm_warga_negara
            Return MyBase.Channel.GetLKm_warga_negara(poEntity)
        End Function
        
        Public Function GetLKm_jabatan() As System.Collections.Generic.List(Of CTM0100SvcRef.LKm_jabatanDTO) Implements CTM0100SvcRef.ICTM0100Svc.GetLKm_jabatan
            Return MyBase.Channel.GetLKm_jabatan
        End Function
        
        Public Function GetLKm_pendidikan() As System.Collections.Generic.List(Of CTM0100SvcRef.LKm_pendidikanDTO) Implements CTM0100SvcRef.ICTM0100Svc.GetLKm_pendidikan
            Return MyBase.Channel.GetLKm_pendidikan
        End Function
        
        Public Function GetRole() As System.Collections.Generic.List(Of CTM0100SvcRef.RoleDTO) Implements CTM0100SvcRef.ICTM0100Svc.GetRole
            Return MyBase.Channel.GetRole
        End Function
    End Class
End Namespace
